//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 09:25:35 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.java2blog.com/xml/book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_java2blog_com.xml.book;
